---
galaxy_info:
  author: Maithili Peetani
  description: Patch linux servers 

  license: license (GNU Lesser General Public License v3.0)

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
      - 18.04
  - name: EL
    versions:
      - 7
      - 8

  galaxy_tags: []

dependencies: []
