---
- hosts: all
  connection: local
  gather_facts: no
  tasks:
  - block:
    - name: determine hosts that are up
      wait_for_connection:
        timeout: 5
      vars:
        ansible_connection: ssh

    - name: add devices with connectivity to the "running_hosts" group
      group_by:
        key: "running_hosts"
    rescue:
      - debug:
          msg: "Cannot connect to {{ inventory_hostname }}"


- hosts: running_hosts
  gather_facts: no
  tasks:
  - command: date

###### After Ansible-2.8 #######

- name: identify reachable hosts
  hosts: all
  gather_facts: false
  ignore_errors: true
  ignore_unreachable: true
  tasks:
  - block:
    - name: this does nothing
      shell: exit 1
      register: result

    always:
    - add_host:
        name: "{{ inventory_hostname }}"
        group: reachable

- name: Converge
  hosts: reachable
  gather_facts: false
  tasks:
    - debug:
        msg: "{{ inventory_hostname }} is reachable"
